### ISSUE TITLE
I Tried to deploy this to Heroku but what are env variables i have to set in heroku

### ISSUE THREAD

**Issue by Nenokkadine** [tks18/gindex-backend#1]
and What addons , Build packs i have to add

**Comment by tks18** [comment]
DBURL= \\ MongoDB url
SITE= \\ Heroku's Site - to Keep Site Alive Eg. https://yourapp.herokuapp.com
EMAILID= \\  Email id from Which OTP will be Sent
ADMINEMAIL= \\ Email Id to Which User Registered Email to be Send
REPLYTOMAIL= \\ Reply to Email id
EMAILPASS= \\ Email Password
EMAILSMTP= \\ smtp of the Mail Client
EMAILPORT= \\ smtp port
EMAILSERVICE= \\ Email Service Provider eg. gmail, yandex, etc..
TOKENSECRET= \\ JWT Secret Pass

**Comment by tks18** [comment]
> and What addons , Build packs i have to add

Nothing Required
Add these Env Variables and Run.

**Comment by Nenokkadine** [comment]
Thanks,
JWT Secret pass -from Where i have to get it from
REPLYTOMAIL mean a message? i.e thanks for Registering bla bla...?
can i give both ADMINEMAIL and EMAILID the Same?
sorry for asking these kind of Questions I am  Noob :(

**Comment by tks18** [comment]
> Thanks,
> JWT Secret pass -from Where i have to get it from
> REPLYTOMAIL mean a message? i.e thanks for Registering bla bla...?
> can i give both ADMINEMAIL and EMAILID the Same?
> sorry for asking these kind of Questions I am a Noob :(

No problem 
1. JWT Secret is some random String. Anything you can keep (But keep it Long). With that secret only we will issue token and verify user's token.

2. Then Email id is for Sending OTP to users.

3. Ya you can keep Both email id and reply to email id same.

4. Also Dont Forget to create a document in Mongodb for a superadmin user with following properties. Otherwise you will not be able to login
         name:
         email: //Required
         admin: true //important
         superadmin: true // Important
         verified: true. // important
         temppassword: null
         role: Super Admin // this is just for display
         temprestricted: false

Thats all required for setup

**Comment by Nenokkadine** [comment]
In MongoDB what application type i have to select Node.js Right?
and  in the DB to add a doc i have to create a database and collection .any specific names for database and collection
"mongodb.net/<dbname>?retryWrites=true&w=majority"
or I have to mention the created db name here?

**Comment by tks18** [comment]
> In MongoDB what application type i have to select Node.js Right?
> and in the DB to add a doc i have to create a database and collection .any specific names for database and collection
> "mongodb.net/?retryWrites=true&w=majority"
> or I have to mention the created db name here?

See for Mongodb Click connect your application and copy the url (Before This add a user for authentication). Paste this url as env variable.

When deployed it will actually create three collections in that add a document in userDB collection.

**Comment by Nenokkadine** [comment]
> > Thanks,
> > JWT Secret pass -from Where i have to get it from
> > REPLYTOMAIL mean a message? i.e thanks for Registering bla bla...?
> > can i give both ADMINEMAIL and EMAILID the Same?
> > sorry for asking these kind of Questions I am a Noob :(
> 
> No problem
> 
> 1. JWT Secret is some random String. Anything you can keep (But keep it Long). With that secret only we will issue token and verify user's token.
> 2. Then Email id is for Sending OTP to users. Reply to Email is when User sends a reply to email, It will come to this email id
> 3. Ya you can keep Both email id and reply to email id same.
> 4. Also Dont Forget to create a document in Mongodb for a superadmin user with following properties. Otherwise you will not be able to login
>    name:
>    email: //Required
>    admin: true //important
>    superadmin: true // Important
>    verified: true. // important
>    temppassword: null
>    role: Super Admin // this is just for display
>    temprestricted: false
> 
> Thats all required for setup

Where i have to add this ?
ok first add the env and it will create a DB and then i have to add it in it?

**Comment by tks18** [comment]
> > > Thanks,
> > > JWT Secret pass -from Where i have to get it from
> > > REPLYTOMAIL mean a message? i.e thanks for Registering bla bla...?
> > > can i give both ADMINEMAIL and EMAILID the Same?
> > > sorry for asking these kind of Questions I am a Noob :(
> > 
> > 
> > No problem
> > 
> > 1. JWT Secret is some random String. Anything you can keep (But keep it Long). With that secret only we will issue token and verify user's token.
> > 2. Then Email id is for Sending OTP to users. Reply to Email is when User sends a reply to email, It will come to this email id
> > 3. Ya you can keep Both email id and reply to email id same.
> > 4. Also Dont Forget to create a document in Mongodb for a superadmin user with following properties. Otherwise you will not be able to login
> >    name:
> >    email: //Required
> >    admin: true //important
> >    superadmin: true // Important
> >    verified: true. // important
> >    temppassword: null
> >    role: Super Admin // this is just for display
> >    temprestricted: false
> > 
> > Thats all required for setup
> 
> Where i have to add this ?
> ok first add the env and it will create a DB and then i have to add it in it?

I have attached screenshots 
Hope that helps 🤟

**Comment by tks18** [comment]
> > > Thanks,
> > > JWT Secret pass -from Where i have to get it from
> > > REPLYTOMAIL mean a message? i.e thanks for Registering bla bla...?
> > > can i give both ADMINEMAIL and EMAILID the Same?
> > > sorry for asking these kind of Questions I am a Noob :(
> > 
> > 
> > No problem
> > 
> > 1. JWT Secret is some random String. Anything you can keep (But keep it Long). With that secret only we will issue token and verify user's token.
> > 2. Then Email id is for Sending OTP to users. Reply to Email is when User sends a reply to email, It will come to this email id
> > 3. Ya you can keep Both email id and reply to email id same.
> > 4. Also Dont Forget to create a document in Mongodb for a superadmin user with following properties. Otherwise you will not be able to login
> >    name:
> >    email: //Required
> >    admin: true //important
> >    superadmin: true // Important
> >    verified: true. // important
> >    temppassword: null
> >    role: Super Admin // this is just for display
> >    temprestricted: false
> > 
> > Thats all required for setup
> 
> Where i have to add this ?
> ok first add the env and it will create a DB and then i have to add it in it?

If the app builds successfully without Application error
This is the response of the website. 
![Screenshot_20200625-223107](https://user-images.githubusercontent.com/54493278/85765270-93da6500-b733-11ea-8a31-588f9c17fb00.jpg)

If this is displayed then in mongodb collections will be created. In that create a document in user collection.

**Comment by Nenokkadine** [comment]
Thanks bro 
Good Work 👍 Keep going.
Closing the issue for now will open again If i have any issues

**Comment by tks18** [comment]
> Thanks bro
> Good Work  Keep going.
> Closing the issue for now will open again If i have any issues

Ok Bro. 🤟
No issues

**Comment by Nenokkadine** [comment]
[hijx-logs-1593144033008.txt](https://github.com/tks18/gindex-backend/files/4835033/hijx-logs-1593144033008.txt)

Heroku app crashed when I tried to login through front end Don't know why 
Attaching logs here.
I used https in the cloudflare worker
https://hijx.herokuapp.com/login --> Like this is this causing problems?

**Comment by Nenokkadine** [comment]
Actually Request access page is working working well
![image](https://user-images.githubusercontent.com/65813999/85819496-776d1580-b791-11ea-8813-5225d7caa53a.png)

**Comment by tks18** [comment]
> [hijx-logs-1593144033008.txt](https://github.com/tks18/gindex-backend/files/4835033/hijx-logs-1593144033008.txt)
> 
> Heroku app crashed when I tried to login through front end Don't know why
> Attaching logs here.
> I used https in the cloudflare worker
> https://hijx.herokuapp.com/login --> Like this is this causing problems?

I will look through this.
But have you been able to login via frontend with that email and password

**Comment by Nenokkadine** [comment]
no i am unable to login

**Comment by Nenokkadine** [comment]
![image](https://user-images.githubusercontent.com/65813999/85822313-36c4ca80-b798-11ea-9fe3-8788fe481d4b.png)
This is the error every time when i try to login.
![image](https://user-images.githubusercontent.com/65813999/85822469-91f6bd00-b798-11ea-94ee-bc37dc42d9e7.png)
this is the doc i created in the DB

**Comment by tks18** [comment]
Wait i have figured out what the issue is 
I have forgot to mention you also have to add a password property in the document. Sorry abt that !

That is because the password in the mongodb superadmin document is null. 

Also you have to hash your password before saving in the document.

**Comment by tks18** [comment]
> ![image](https://user-images.githubusercontent.com/65813999/85822313-36c4ca80-b798-11ea-9fe3-8788fe481d4b.png)
> This is the error every time when i try to login.
> ![image](https://user-images.githubusercontent.com/65813999/85822469-91f6bd00-b798-11ea-94ee-bc37dc42d9e7.png)
> this is the doc i created in the DB

Use this generator to generate hash 
https://www.browserling.com/tools/bcrypt
Use 10 rounds for salting

**Comment by tks18** [comment]
> ![image](https://user-images.githubusercontent.com/65813999/85822313-36c4ca80-b798-11ea-9fe3-8788fe481d4b.png)
> This is the error every time when i try to login.
> ![image](https://user-images.githubusercontent.com/65813999/85822469-91f6bd00-b798-11ea-94ee-bc37dc42d9e7.png)
> this is the doc i created in the DB

![IMG_20200626_104058_1~2](https://user-images.githubusercontent.com/54493278/85822918-b43d0a80-b799-11ea-8d11-18de0461bb56.jpg)

Add a password property in your document and try to login thats the issue

**Comment by Nenokkadine** [comment]
Login done
![image](https://user-images.githubusercontent.com/65813999/85823533-41cd2a00-b79b-11ea-80a1-235f3c247b29.png)
How these can be configured

**Comment by tks18** [comment]
> Login done
> ![image](https://user-images.githubusercontent.com/65813999/85823533-41cd2a00-b79b-11ea-80a1-235f3c247b29.png)
> How these can be configured

That i have done it specifically for my drive. 
So you have to change links in home.vu

**Comment by Nenokkadine** [comment]
ok fine
![image](https://user-images.githubusercontent.com/65813999/85824046-80171900-b79c-11ea-9ae8-a51f161d9534.png)
Password change is not working.

**Comment by tks18** [comment]
> ok fine
> ![image](https://user-images.githubusercontent.com/65813999/85824046-80171900-b79c-11ea-9ae8-a51f161d9534.png)
> Password change is not working.

That's the issue i am currently working on. 
Will update once i find out.

**Comment by Nenokkadine** [comment]
Ok thanks for the Support ✌👌

**Comment by tks18** [comment]
> ok fine
> ![image](https://user-images.githubusercontent.com/65813999/85824046-80171900-b79c-11ea-9ae8-a51f161d9534.png)
> Password change is not working.

I see that navbar is hiding some content.
Add this class to body tag in cloudflare worker file 
"has-navbar-fixed-top" to fix padding issue

**Comment by Nenokkadine** [comment]
![image](https://user-images.githubusercontent.com/65813999/85824931-8f976180-b79e-11ea-8f87-72665202c319.png)
I Changed it my self Thanks

**Comment by tks18** [comment]
I have fixed that password issue. 
Accordingly Change your deployment. 🤟
