### ISSUE TITLE
How to configure? 

### ISSUE THREAD

**Issue by askfriends** [tks18/gindex-backend#20]
hi bro..
this is very good project. i want to use this project for my GIndex website.

but i am new to this thing..so when i click on deploy button, it asks MongoDB URL, what is it and how to create that?

you must be busy but if you could provide all dummy details to use in the fields it would be really helpful.
You could update your readme file and add those instructions.

**Comment by LeeluPradhan** [comment]
Hey @askfriends please follow [guide](https://telegra.ph/Google-Drive-Ultimate-Index-07-04) and join [telegram group](https://t.me/joinchat/LVLR1U5Gs_9pFwLPoF1RGQ) for further information/help
Thanks :)
