### ISSUE TITLE
Returning to home page

### ISSUE THREAD

**Issue by ShakilReddy** [tks18/gindex-backend#6]
Whenever I try to login as superadmin, I'm coming back to Home page. 

If I try my mail in home page, it says There's some error with your network.

**Comment by tks18** [comment]
Bro what is the frontendurl u have defined in heroku.
Note that this url must have http or https and do not put / at the end. 
This will solve the issue

**Comment by ShakilReddy** [comment]
> Bro what is the frontendurl u have defined in heroku.
> Note that this url must have http or https and do not put / at the end.
> This will solve the issue



> Bro what is the frontendurl u have defined in heroku.
> Note that this url must have http or https and do not put / at the end.
> This will solve the issue

https://findex.noobmaster69.workers.dev

**Comment by tks18** [comment]
> > Bro what is the frontendurl u have defined in heroku.
> > Note that this url must have http or https and do not put / at the end.
> > This will solve the issue
> 
> > Bro what is the frontendurl u have defined in heroku.
> > Note that this url must have http or https and do not put / at the end.
> > This will solve the issue
> 
> https://findex.noobmaster69.workers.dev

This is right 

In worker file what have you given as backendurl
That should also follow the same principle 
Do not put a / at the end

**Comment by ShakilReddy** [comment]
> > > Bro what is the frontendurl u have defined in heroku.
> > > Note that this url must have http or https and do not put / at the end.
> > > This will solve the issue
> > 
> > 
> > > Bro what is the frontendurl u have defined in heroku.
> > > Note that this url must have http or https and do not put / at the end.
> > > This will solve the issue
> > 
> > 
> > https://findex.noobmaster69.workers.dev
> 
> This is right
> 
> In worker file what have you given as backendurl
> That should also follow the same principle
> Do not put a / at the end

Thanks Anna, issue solved.

**Comment by tks18** [comment]
No problem 🤙🤙
