### ISSUE TITLE
Need a renaming

### ISSUE THREAD

**Issue by ShakilReddy** [tks18/gindex-backend#7]
Mails like OTP one (We have accepted your request) and Account verified are mailed as Glory to Heaven - Support instead of <indexname> - Support

Also can we change the loading image when we click folders which is "Porumayaga Irukkavum".

**Comment by tks18** [comment]
I am currently working on email templates
Will do that

**Comment by tks18** [comment]
> Mails like OTP one (We have accepted your request) and Account verified are mailed as Glory to Heaven - Support instead of - Support
> 
> Also can we change the loading image when we click folders which is "Porumayaga Irukkavum".

If you need to change the lazyload image, then you need to build the assets
